package com.carwash.security;

public enum Permission {
    USER_SELF_MANAGE, USER_ADMIN, VEHICLE_SELF_MANAGE, VEHICLE_OPERATE,
    SERVICE_READ, SERVICE_MANAGE, BOOKING_SELF_MANAGE, BOOKING_OPERATE,
    QUEUE_SELF_READ, QUEUE_OPERATE, NOTIFICATION_SELF_READ, REPORT_READ, ROLE_ASSIGN
}
