spring.application.name=${SPRING_APP_NAME}
server.port=${SERVER_PORT}
carwash.security.password.bcrypt-strength=${SECURE_PASSWORD_BCRYPT_STRENGTH}
carwash.security.password.min-length=${SECURE_PASSWORD_MIN_LENGTH}
carwash.security.password.max-utf8-bytes=${SECURE_PASSWORD_MAX_UTF8_BYTES}
carwash.security.jwt.issuer=${SECURE_JWT_ISSUER}
carwash.security.jwt.access-token-ttl=${SECURE_JWT_ACCESS_TOKEN_TTL}
carwash.security.jwt.secret=${SECURE_JWT_SECRET}
