spring.application.name=carwash-booking-queue-system
server.port=8080
carwash.security.password.bcrypt-strength=10
carwash.security.password.min-length=12
carwash.security.password.max-utf8-bytes=72
carwash.security.jwt.issuer=carwash-booking-queue-system
carwash.security.jwt.access-token-ttl=20m
# carwash.security.jwt.secret=${CARWASH_SECURITY_JWT_SECRET}
carwash.security.jwt.secret=VGhpcyBpcyBhIGRldGVybWluaXN0aWMgdGVzdC1vbmx5IDMyLWJ5dGUgc2VjcmV0IQ==
