package com.carwash.audit.domain;

/** Stable, non-secret action catalogue. Refund names are reserved but not emitted until payments exist. */
public enum AuditAction {
    LOGIN_SUCCESS, LOGIN_FAILURE, BEARER_AUTHENTICATION, AUTHORIZATION_DENIED,
    ROLE_ASSIGNED, TENANT_MEMBERSHIP_ASSIGNED, TENANT_MEMBERSHIP_REPLACED, TENANT_MEMBERSHIP_REMOVED,
    BUSINESS_REGISTERED, BUSINESS_UPDATED, BUSINESS_ACTIVATED, BUSINESS_DEACTIVATED,
    BRANCH_CREATED, BRANCH_UPDATED, BRANCH_ACTIVATED, BRANCH_DEACTIVATED,
    OPERATING_SCHEDULE_REPLACED, TEMPORARY_CLOSURE_CREATED, TEMPORARY_CLOSURE_CANCELLED,
    SERVICE_DEFINITION_CREATED, SERVICE_DEFINITION_UPDATED, SERVICE_DEFINITION_ACTIVATED,
    SERVICE_DEFINITION_DEACTIVATED, SERVICE_DEFINITION_DELETED,
    SERVICE_OFFERING_CREATED, SERVICE_OFFERING_UPDATED, SERVICE_OFFERING_ACTIVATED,
    SERVICE_OFFERING_DEACTIVATED,
    BOOKING_CREATED, BOOKING_UPDATED, BOOKING_CANCELLED, BOOKING_RESCHEDULED,
    BOOKING_CONFIRMED, BOOKING_DELETED,
    VEHICLE_CREATED, VEHICLE_UPDATED, VEHICLE_DELETED,
    QUEUE_CREATED,
    QUEUE_POSITION_OVERRIDDEN, QUEUE_CALLED_NEXT, QUEUE_CALLED, QUEUE_SERVICE_STARTED,
    QUEUE_SERVICE_COMPLETED, QUEUE_REMOVED,
    PLATFORM_ADMIN_OPERATION, AUDIT_RECORDS_READ,
    REFUND_REQUESTED, REFUND_COMPLETED, REFUND_FAILED
}
