package com.carwash.shared.api.error;

public enum ApiErrorCode {
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    INVALID_PARAMETER,
    MISSING_PARAMETER,
    UNKNOWN_PROPERTY,
    BUSINESS_RULE_VIOLATION,
    RESOURCE_NOT_FOUND,
    INVALID_CREDENTIALS,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    INTERNAL_ERROR
}
